### ISSUE TITLE
Cannot find Java 1.8 or higher

### ISSUE THREAD

**Issue by tofflos** [oracle/javavscode#10]
When I press Ctrl-Shift-P and launch New Java Project I get the following error message: "Cannot find Java 1.8 or higher".

I've read the extension documentation which says the JDK is being searched for in the following locations:
* jdk.jdkhome setting (workspace then user settings)
* java.home setting (workspace then user settings)
* JDK_HOME environment variable
* JAVA_HOME environment variable
* current system path

So I launched the integrated terminal and verified that javac is on the path:

```
PS C:\Users\Erik> javac --version
javac 21
```

Visual Studio Code seems to think that javac is on the path... So what is the extension looking for when the documentation says it's searching for the JDK on the current system path?

**Comment by arvindaprameya** [comment]
@tofflos The settings.json needs to have the path set to JDK's "Home" directory

This can be invoked using "View->Command Palette->**Preferences**: **Open User Settings (JSON)**" 
and the value its expected is :
  "jdk.jdkhome": "/Users/joe/Downloads/release-versionjdk/jdk-21.0.1.jdk/Contents/Home"

**Comment by tofflos** [comment]
Thank you. It's just that I was expecting it to find javac by itself since the documentation says that the plugin does search the system path. Here is a real world example for Windows 10 and the Microsoft Build of OpenJDK 21:

```json
"jdk.jdkhome": "C:\\Program Files\\Microsoft\\jdk-21.0.0.35-hotspot"
````

**Comment by arsapre** [comment]
I tried reproducing this locally on windows 11 machine.

Removed all installed JDK. No JAVA_HOME environment variable set.
Started vscode and pressed Ctrl-Shift-P -> launch New Java Project 
Got the following error message: "Cannot find Java 1.8 or higher". This is expected.

Downloaded windows files (msi & zip) from https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-21

Extracted the downloaded zip file to a local folder, and pointed jdk.jdkhome to this path in settings.json file.
Restarted vscode and pressed Ctrl-Shift-P -> launch New Java Project
I didn't get any error message and vscode prompted for further inputs.

Installed msi and repeated the above steps. Vscode didn't show any error message.



Could you share the outpur from Oracle Java SE Language Server (from Output window), when you press  Ctrl-Shift-P -> launch New Java Project

I am expecting output something like this:

> Launching Oracle Java SE Language Server with <path> and userdir <dir path>
> LSP server launching: 2324
> LSP server user directory: <Dir name>
> ....
> Code Name                                          Version                               State    
> -------------------------------------------------- ------------------------------------- ---------
> org.netbeans.modules.options.java                  1.36                                  Enabled  
> ....

**Comment by Achal1607** [comment]
Closing this issue, since it is stale.
