### ISSUE TITLE
Support for Preview Features

### ISSUE THREAD

**Issue by sebfisch** [oracle/javavscode#13]
Here is a file `Hello.java` using [JEP 445: Unnamed Classes and Instance Main Methods (Preview)](https://openjdk.org/jeps/445)

```java
void main() {}
```

The project has a JDK 21 configured via Maven using

```xml
<properties>
  <maven.compiler.release>21</maven.compiler.release>
</properties>
```

and

```xml
<configuration>
  <release>21</release>
  <compilerArgs>--enable-preview</compilerArgs>
</configuration>
```

inside the `maven-compiler-plugin`. Running `mvn clean compile` compiles `Hello.java` without errors, but VSCode with the extension [Java Platform Support](https://marketplace.visualstudio.com/items?itemName=Oracle.oracle-java) displays the error

```
unnamed classes are a preview feature and are disabled by default.
  (use --enable-preview to enable unnamed classes)
```

I put

```json
{
  "jdk.runConfig.arguments": "--enable-preview"
}
```

into my `settings.json` without success.

Are Preview Features supported by this extension?

**Comment by Achal1607** [comment]
- The configuration setting that you are using of the extension `"jdk.runConfig.arguments"`, directly passes the argument to the maven and not to the java compiler as shown in the attached screenshot. So, if you want to pass any argument to the maven or gradle then this configuration is useful. 
<img width="1111" alt="Screenshot 2023-10-20 at 3 23 00 PM" src="https://github.com/oracle/javavscode/assets/55803675/aa70a07a-3c35-4f69-9bc0-73986e3d79ba">

- Now coming to the preview features usage, if you want to use preview features in a single Java file then it can be done by using the following configuration setting in Users JSON of VS Code.
```
{
    "jdk.runConfig.vmOptions":"--source 21 --enable-preview",
}
```
Showing example about in the above case:
<img width="487" alt="image" src="https://github.com/oracle/javavscode/assets/55803675/d8b427bc-87ff-47e0-83e8-9a6415465760">

**Comment by sebfisch** [comment]
Thank you for your help! Unfortunately, the error is not gone, even after placing the option you mentioned in the project and/or user settings and reloading the window.

To be clear: The error does not appear when running the code or compiling it with Maven. It is displayed in VSCode when opening the file:

![Preview](https://github.com/oracle/javavscode/assets/38267/7f777e85-ee13-4283-bb3b-1a037bdb3a66)

Do I need a different configuration to enable support for preview features in the language server?

**Comment by Achal1607** [comment]
With maven and Gradle projects, I don't think there is any option to enable the preview feature in the extension within this version apart from the maven-compiler-plugin option that you mentioned earlier.
The option that I mentioned earlier can be used if you have a standalone Java file to enable the preview feature and compile the project using the extension, without any Maven or Gradle project.

**Comment by lahodaj** [comment]
For Maven project, please try to use:
```
                    <compilerArgs>
                        <arg>--enable-preview</arg>
                    </compilerArgs>
```
instead of:
```
                    <compilerArgs>--enable-preview</compilerArgs>
```
(note the nested `<arg>`).

Thanks.

**Comment by sebfisch** [comment]
Thanks! Correcting the `<compilerArgs>` declaration in the `.pom` file fixes the issue.
