### ISSUE TITLE
Wrong instructions to build the extension

### ISSUE THREAD

**Issue by oscarvarto** [oracle/javavscode#140]
Hi!

I have seen the BUILD.md file in the repo
https://github.com/oracle/javavscode/blob/main/BUILD.md#fetching-and-building-netbeans-code
and it has these instructions:
```
$ git clone https://github.com/apache/netbeans.git
$ cd netbeans/
$ git checkout 21
$ cd ..
# the following target requires git executable to be on PATH:
$ ant apply-patches
$ ant build-netbeans
```

It makes no sense to to the `cd ..` step to me. Maybe a typo? What are the correct instructions?

**Comment by anthonyvdotbe** [comment]
@Achal1607 I agree with @oscarvarto that the `cd ..` doesn't make sense. Please re-evaluate this issue
