### ISSUE TITLE
[22.0.1] Noisy popups from loading Gradle project (Gradle 8.8, Java 22.0.1)

### ISSUE THREAD

**Issue by hrstoyanov** [oracle/javavscode#167]
Getting noise popups for some kind of Gradle 8.8 import false errors, for a Java 22.0.1 projects, which builds fine outside the IDE:
<img width="508" alt="Screenshot 2024-06-02 at 8 15 09 AM" src="https://github.com/oracle/javavscode/assets/5327044/bbe264b9-b140-4906-958a-5054032fb3c5">

This are all flat sub-projects, but defined with symbolic links

**Comment by Achal1607** [comment]
Hey @hrstoyanov 
Can you please provide any reproducible steps if possible?

**Comment by Achal1607** [comment]
I don't have Gitlab account, is there any other option?
