### ISSUE TITLE
Folder is empty when creating a new project.

### ISSUE THREAD

**Issue by NdYGA** [oracle/javavscode#178]
Good afternoon, Everyone!
    I would be grateful if the Community could assist me with the following matter.

Could You help or clarify - perhaps this is normal behavior. But my expectations are a little different.

Scenario:

- Opening a folder in VSCode
- Executing the "JAVA: New Project" command
- Select "Java with Gradle" => "Java Application"
- Specify the path of the project folder
- Accept the project package configuration

The output is: an empty project folder. 

I was expecting to get the standard gradle project structure.
Maybe I'm missing a configuration setting?

Thank You for taking the time to do this.

===================================

Version: 1.90.1
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:01:24.262Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22000

------------------------------------------------------------
Gradle 8.8
------------------------------------------------------------

Build time:   2024-05-31 21:46:56 UTC
Revision:     4bd1b3d3fc3f31db5a26eecb416a165b8cc36082

Kotlin:       1.9.22
Groovy:       3.0.21
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          22.0.1 (Oracle Corporation 22.0.1+8-16)
OS:           Windows 11 10.0 amd64

------------------------------------------------------------
java version
------------------------------------------------------------

java version "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

vscode json settings
    "jdk.jdkhome": "H:/jdk-22.0.1",
    "explorer.excludeGitIgnore": true,
    "jdk.advanced.disable.nbjavac": true

**Comment by Achal1607** [comment]
Hey @NdYGA, my initial guess would be it is unable to download gradle wrapper. Are you behind a VPN or some sort of network which blocks download from some sites?

**Comment by NdYGA** [comment]
Sometimes it's very helpful to look at a problem from a different angle... Thanks, this is exactly what I needed! 

Added  **nbcode64.exe (3000)** to firewall exceptions - problem completely solved.
  **H:\vsCode\data\extensions\oracle.oracle-java-22.0.1\nbcode\bin\nbcode64.exe**

Please accept my sincere thanks for Your time!
