### ISSUE TITLE
Show constructor signature in hover information

### ISSUE THREAD

**Issue by chriskriel** [oracle/javavscode#182]
When hovering over a method the hover information / tool-tip correctly shows the method signature. However for a constructor it incorrectly (in my opinion) shows class information and not the signature. 

The only why to see the constructor's signature is to hover over a numeric argument to the constructor, which is not always available.

**Comment by chriskriel** [comment]
To be more clear, said "numeric argument" must be a constant, otherwise the tool-tip shows the variable declaration.

**Comment by Achal1607** [comment]
PR raised in Netbeans: https://github.com/apache/netbeans/pull/7654
