### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.source.tree.StringTemplateTree

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#193]
The extension is unusable due to exceptions caused by

> java.lang.ClassNotFoundException: com.sun.source.tree.StringTemplateTree

with `jdk.advanced.disable.nbjavac` set to `true` and `jdk.jdkhome` pointing to a JDK 24 build.
Probably because NetBeans hasn't removed its String Templates support yet, but the JDK has.

**Comment by lahodaj** [comment]
I believe this will be resolved when we upgrade to NetBeans 23 as the backend.

**Comment by Achal1607** [comment]
Merged in 23.0.0
