### ISSUE TITLE
Formatter doesn't support `{@return foo}`

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#194]
The formatter messes up Javadoc like `{@return foo}`.

For example formatting this:

```java
    /**
     * {@return foo}
     */
    String bar() {
        return null;
    }
```

Actual:

```java
    /**
     * {
     *
     * @return foo}
     */
    String bar() {
        return null;
    }
```

Expected:

```java
    /**
     * {@return foo}
     */
    String bar() {
        return null;
    }
```

**Comment by naren2605** [comment]
create a [issue](https://github.com/apache/netbeans/issues/7640) in netbeans related to this issue

**Comment by naren2605** [comment]
### verification of fix
before formatting bar method:
<img width="606" alt="image" src="https://github.com/user-attachments/assets/4bf63d4c-87c9-428a-be39-000f5b9d3545">



after formatting bar method:

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/26164293-2d77-4542-920b-3c92bb765e22">
