### ISSUE TITLE
test runner incorrectly processes test names

### ISSUE THREAD

**Issue by robaho** [oracle/javavscode#217]
If you have two tests named with the same prefix, the test runner shows them as nested.

For example, `ensureAllElementsAreRead` and `ensureAllElementsAreReadUsingThread` it shows the latter nested under the first.

See attached screenshot.
<img width="1259" alt="Screen Shot 2024-07-25 at 9 42 45 AM" src="https://github.com/user-attachments/assets/e4617218-dc32-49f7-8d86-8ab1c37f6e9b">

**Comment by sid-srini** [comment]
Hi @robaho. Thanks for providing a screenshot of the issue. Would you please provide some more details about your environment? such as:
1. The version of VS Code you're using;
2. The version of the extension you're using;
3. The version of JUnit you are using;
4. Whether the project is a maven or a gradle project; and which version is in use.
5. Any other information that you may think might be useful for us to reproduce this issue. 

Thank you.

**Comment by robaho** [comment]
```
Version: 1.91.1 (Universal)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 21.6.0
```

Oracle extension version v22.1.1
Gradle
JDK 21

As I mentioned in the related issue, you can install the project from https://github.com/robaho/closablequeue

**Comment by naren2605** [comment]
rca: issue is due to grouping based on prefix and leaving extra entries in explorer panel which are not getting right test status updates
 
 fix:  will be removing grouping
