### ISSUE TITLE
jdk.jdkhome doesn't work as documented

### ISSUE THREAD

**Issue by robaho** [oracle/javavscode#22]
Per the documentation:

> - jdk.jdkhome setting (workspace then user settings)
> - java.home setting (workspace then user settings)
> - JDK_HOME environment variable
> - JAVA_HOME environment variable
> - current system path

but if you try to set this in a workspace setting it says:

<img width="1056" alt="image" src="https://github.com/oracle/javavscode/assets/4958833/41ab912e-a6d9-4c4b-9cd3-acf269f059d2">

 This make it nearly impossible to work with multiple jdks in multiple projects.

Why not use the gradle specified jdk and search process?

**Comment by robaho** [comment]
Actually, it looks like maybe it still works, and just that the message/highlighting is incorrect in the settings file.

**Comment by Achal1607** [comment]
Ok, then the messaging will be updated in the next version of the extension.

**Comment by robaho** [comment]
One other note, the JDK setting per workspace only makes sense if the jdk.userdir is set to local for that particular workspace. 

It seems jdk.userdir set to global should mean use a shared language server for all workspaces where it is set to global. 

Ideally, I think the best thing would be to remove the jdk.userdir setting and let the system determine if it needs a new instance based on the required jdk for that workspace.

**Comment by lahodaj** [comment]
My proposal is to drop the `jdk.userdir` setting for now (having a userdir only per workspace, which is the default now), and changing the scope of the `jdk.jdkhome` setting from `machine` to `machine-overridable`. Would be good to double-check that the Remote SSH usages works after this change, but IIRC I tried long time ago, and it worked.

**Comment by lahodaj** [comment]
Just to elaborate more `machine-overridable` scope allows to override a setting in a specific workspace. See:
https://code.visualstudio.com/api/references/contribution-points

**Comment by robaho** [comment]
I think that is a good idea. Otherwise when using a global ls all open projects appear in the Java projects pain - which is confusing. And if each wants a different JDK all sorts of things break.
