### ISSUE TITLE
"Delete Oracle Java extension cache for this workspace" fails with an error

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#221]
Attempting to execute the command says:

![image](https://github.com/user-attachments/assets/f06dd257-a47e-4cf1-a00e-2a5793b3c30e)

which seems logical. Red Hat's extension has a similar command and restarts VS Code, most likely to avoid issues like this.

**Comment by Achal1607** [comment]
Resolved in #245
