### ISSUE TITLE
Class outline/structure missing in some cases

### ISSUE THREAD

**Issue by hrstoyanov** [oracle/javavscode#23]
I see nothing when I open OUTLINE in thge Explorer  panel?

**Comment by Achal1607** [comment]
The Outline view is a separate section in the bottom of the File Explorer. When expanded, it will show the symbol tree of the currently active editor. So you need to have a Java file opened then only you would be able to see the outline of that file like functions and classes.
<img width="308" alt="image" src="https://github.com/oracle/javavscode/assets/55803675/7a69e494-492c-437f-9704-d66b178bb7d6">

**Comment by hrstoyanov** [comment]
Take a look at the screenshot - I have opened a Java file, even debugging session going... but my OUTLINE sections is empty?
<img width="1680" alt="Screenshot 2023-10-21 at 12 57 00 AM" src="https://github.com/oracle/javavscode/assets/5327044/474df06c-2279-4122-985d-e4490e47fab8">

**Comment by Achal1607** [comment]
Please can you provide logs or some more info on how to reproduce the issue, so that we can investigate further?

**Comment by hrstoyanov** [comment]
Ok, here is the code to reproduce it:
https://github.com/hrstoyanov/vscodeJavaIssue

**Comment by Achal1607** [comment]
I also tried to run the program and for me as well it doesn't show anything in the outline tab. So, we need to investigate more around this issue.

**Comment by Achal1607** [comment]
FYI, raised a PR to close this issue in netbeans:
https://github.com/apache/netbeans/pull/6642

**Comment by Achal1607** [comment]
Resolved and merged PR
