### ISSUE TITLE
vscode reports a need to upgrade Gradle to an earlier version for JDK-21

### ISSUE THREAD

**Issue by robaho** [oracle/javavscode#29]
I am using JDK-21 and Gradle 8.4, but when I open the project it tells me that the current project is not supported by Gradle 8.4 and I should install 8.3-rc-1.

It seems to work of with 8.4.

<img width="483" alt="image" src="https://github.com/oracle/javavscode/assets/4958833/32fbd82e-9644-45b3-bfa9-b48f9315a868">

**Comment by hrstoyanov** [comment]
I get the same, but I am not sure this is related to to this Java VSCode plugin - I get the same  stupid warning with the latest IntelliJ for my project that uses Gradle 8.4/Java 21.  I posted some to reproduce [unrelated issue here](https://github.com/hrstoyanov/vscodeJavaIssue), but you should see the above warning as well when you open the code.
Seems like the warning is harmless though and quickly disappers?

**Comment by robaho** [comment]
It seems you get it once for every sub project.

**Comment by hrstoyanov** [comment]
This is a  Gradle 8.4 issue, to be fixed in 8.5 apparently:
https://github.com/gradle/gradle/issues/25574

**Comment by Achal1607** [comment]
FYI: Fix available in NB21: https://github.com/apache/netbeans/pull/6807

**Comment by Achal1607** [comment]
Merged https://github.com/oracle/javavscode/pull/128
