### ISSUE TITLE
Oracle Java SE Language Server not enabled

### ISSUE THREAD

**Issue by Ywandung-Lyou** [oracle/javavscode#297]
In log, there is "cannot run on older versions of Java than Java 17", "Oracle Java SE Language Server not enabled". However, the introduction says that the extension supports JDK 8.

What should be done to run language server on Java 17 and to debug my projects on JDK 8?

**Comment by Achal1607** [comment]
Thanks @Ywandung-Lyou for trying out the extension.
- Set `jdk.jdkhome` to point to JDK-17 or JDK17+ to run the language server.
- Set `jdk.project.jdkhome` to JDK 8 in your case for debugging your project.

**Comment by Achal1607** [comment]
Closing this issue for now due to inactivity, if you have any more queries feel free to reopen this issue.
