### ISSUE TITLE
How to create jar file for the project 

### ISSUE THREAD

**Issue by Ywandung-Lyou** [oracle/javavscode#298]
As the title says, does the extension support creating the jar file for a Spring Maven project?
If so, could you show me the process?

**Comment by sid-srini** [comment]
Hi @Ywandung-Lyou. Thanks for reaching out. 
You may use the ["Compile Workspace" command](https://github.com/oracle/javavscode?tab=readme-ov-file#supported-actions) to trigger the Maven build.

Commands in VS Code are launched either by the keyboard shortcut ctrl+shift+P (cmd+shift+P on macOS) or by typing `>` in the top search bar.
<img width="435" alt="Screenshot 2024-10-24 at 3 58 48 PM" src="https://github.com/user-attachments/assets/1a989df5-65c8-4fd2-b045-0203c068018d">

The jar would be created in the target directory, as configured in your maven project file. By default, maven places the *target/* directory in your project's root folder i.e. the one containing the *pom.xml*.

I hope this helps.
