### ISSUE TITLE
Renaming the class containing the main method does not update pom.xml

### ISSUE THREAD

**Issue by tofflos** [oracle/javavscode#30]
Create a new Maven project using Ctrl-Shift-P Java New Project.
Check that it's possible to Run the project.
Check that pom.xml contains an entry similar to `<exec.mainClass>com.example.Main</exec.mainClass>` in the properties section.

Open the class containing the main method, select the class name, press F2, and rename it.
Note that the file has been renamed.
Note that it's no longer possible to Run the project.
Note that the pom.xml entry `<exec.mainClass>com.example.Main</exec.mainClass>` hasn't been updated.

**Comment by Achal1607** [comment]
FYI Raised a PR on netbeans side:
https://github.com/apache/netbeans/pull/7104
