### ISSUE TITLE
Cannot add a custom library without creating a Maven or Gradle project

### ISSUE THREAD

**Issue by Arebusf21** [oracle/javavscode#315]
I would like to use the Oracle Java Extension for VSCode, but cannot find a way to point to my custom library folder.
I don't want to use Maven or Gradle as a project, I want to keep it simple.
Is there a simple way to do this?

**Comment by sid-srini** [comment]
Hi @Arebusf21. Thanks for reaching out. 

The workspace's [*Run Configuration* settings](https://github.com/oracle/javavscode?tab=readme-ov-file#run-configurations-panel),  specifically the *VM Options* may be set with the necessary [Java options](https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#standard-options-for-java) such as ***Classpath*** `-cp`, ***Module Path*** `--module-path` to specify the paths to the library jars you need to use. 

I hope this helps. Please let us know if you have any other questions or issues. Thanks.

**Comment by eleses** [comment]
This doesn't fix "find cannot find symbol" errors in the editor itself though, i.e. `-cp` and so forth don't affect the classpath used by the editor/lint. In the Red Hat extension there's a `java.project.referencedLibraries` but that's ignore in the Oracle extension.
