### ISSUE TITLE
String templates break formatting

### ISSUE THREAD

**Issue by gabro** [oracle/javavscode#35]
It seems that using string templates ([a preview feature in Java 21](https://openjdk.org/jeps/430)) breaks formatting in VS Code.

Specifically, whenever the file contains a string template like `STR."Hello \{name}"` the formatted trips up and starts adding newlines at each run.

Here's a GIF where I repeatedly format the file:

![2023-10-23 12 12 42](https://github.com/oracle/javavscode/assets/691940/e18724ad-9b67-46d5-b04b-c93448038a2b)

Removing the string template makes the issue disappear.

**Comment by Achal1607** [comment]
Resolved and merged PR
