### ISSUE TITLE
Run/Debug with launch.json configuration using "mainClass" fails with "internal error"

### ISSUE THREAD

**Issue by robaho** [oracle/javavscode#36]
I am using vscode 1.83.1

I have a valid configuration, like:

```
        {
            "type": "jdk",
            "name": "Main",
            "request": "launch",
            "mainClass": "cff.package.main.Main",
            "args": "dev",
            "vmArgs": "-Dmy-services=etc/services/dev-services.properties -Dorg.jboss.logging.provider=jdk"
        },
```

but when I run it I get the attached:

![image](https://github.com/oracle/javavscode/assets/4958833/5dfc38b5-640a-47e0-9d70-a03692f8c6ef)

I am only able to run things using Gradle tasks or the 'tooltip runner' as in:

![image](https://github.com/oracle/javavscode/assets/4958833/c3ec7a65-7be1-46d2-bcfc-aea0c3f385ce)

**Comment by robaho** [comment]
I was able to narrow down the cause.

This fails if the launch.json specifies a `mainClass` attribute. This makes it impossible to use run/debug when a project contains multiple top-level entry points.

The only option that works is to go to the main class and use the Intellisense to run the class.

**Comment by Achal1607** [comment]
I looked into this issue. Actually you need to provide absolute path to the `mainClass`.  Please try using absolute path.

Example configuration:
```
{
    "version": "0.2.0",
    "configurations": [
    {
        "type": "jdk",
        "request": "launch",
        "name": "Main",
        "mainClass": "/Users/atalati/vscode-extension/testingProjects/simpleMavenProject/src/main/java/org/yourcompany/yourproject/SimpleMavenProject.java",
        "args": "dev",
        "vmArgs": ""
    }
    ]
}
```

**Comment by Achal1607** [comment]
Also, please can you update here if it worked or not?

**Comment by stacktracer** [comment]
@Achal1607 this worked for me -- thank you :pray: 

Having a field called `mainClass` that expects a _path_ to a _source_ file is ... surprising. Renaming it to something like `mainSourceFile` might save users some frustration.
