### ISSUE TITLE
Problems launching and debugging JavaFX application

### ISSUE THREAD

**Issue by hallvard** [oracle/javavscode#37]
I recently tried to use your VSCode extension for working on my multi-module JavaFX project at https://github.com/hallvard/halban. It seems to pick up the project structure correctly. I could run ordinary classes with a main method (used for simple testing).

However, I could not launch my app using Run or Debug (Application subclass in sokoban-app module), presumably since it needs to use man javafx:run instead. It would be great if it could detect that the class is a JavaFX application class, and launch it accordingly. 

After manually launching in the terminal with mvnDebug I could attach the VSCode debugger, but all my breakpoint became unverified, so in practice, debugging didn't work.

Launching ordinary tests does not seem to work, either, the line in the Test Results or Testing panel just keeps spinning.

**Comment by Achal1607** [comment]
You can add custom run and debug configurations in `launch.json` file  inside `.vscode` dir, and then can you try debugging and running your project?

**Comment by Achal1607** [comment]
Since there is no recent acitvity on this issue, closing it for now. But, if you still face any problem feel free to reopen this issue or file a fresh issue.
