### ISSUE TITLE
The extension tells VS Code that it can format XML, but nothing actually happens when formatting XML

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#44]
The extension tells VS Code that it can format XML,

![image](https://github.com/oracle/javavscode/assets/15714253/3febd18e-f47f-4c72-ae7f-5a5e973800f5)

but nothing actually happens when formatting XML.

**Comment by Achal1607** [comment]
Duplicate of #24

**Comment by anthonyvdotbe** [comment]
My bad
