### ISSUE TITLE
Provide an extension pack

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#45]
The extension has support for Maven/Gradle projects, running/debugging/testing, ... so it's unclear (for me at least) which other common Java extensions (in particular those in the Extension Pack for Java and Gradle for Java):

* are complementary
* are incompatible
* are useful for the time being, but will become obsolete in due time as support is added to this extension
* ...

With an extension pack, people wouldn't have to think about what is the current best set of extensions for a comprehensive developer experience.

As an example: for Maven projects, the extension currently doesn't provide any support for editing the `pom.xml` (even though [it says it's able to format XML](https://github.com/oracle/javavscode/issues/44)). So as of today the extension pack would include the "Maven for Java" and "XML" extensions. But maybe sometime in the future, the extension will provide sufficient support for editing the POM that those extensions would no longer be necessary. At that point they could simply be removed from the extension pack.

**Comment by Achal1607** [comment]
This is something we would look in the future but closing for now as it is not in our current plans. 
Thanks for your suggestion

**Comment by anthonyvdotbe** [comment]
@Achal1607 it seems a bit contradictory that the issue is labeled `wontfix`, but your comment suggests that this might be done in the future. Why not leave the issue open with a label `future` or `postponed` or such? That way I'll still be notified when this is eventually implemented and I won't have to consider filing a new issue for the same enhancement every couple years.
