### ISSUE TITLE
Given an exact variable match, autocompletion with dot should always use that

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#54]
Consider the following:

![image](https://github.com/oracle/javavscode/assets/15714253/916e0974-8d78-47ee-82d0-cbbd40f16ae7)

When I type a dot at this point, it autocompletes to `fooUfo`, which just doesn't make sense to me. I'm literally typing `foo.`, because that's exactly what I want. I understand that `fooUfo` is higher up the list for some reason, but in cases where there's an exact variable match, that list should be ignored.

```java
class Test {

    static void run() {
        String foodoo = "";
        String foo = "";
        Integer fooUfo = 2;
        int c = foo
    }

}
```

**Comment by anthonyvdotbe** [comment]
Just to demonstrate how annoying this is: I'm trying to type `if(locale.getLanguage() ...)`:

https://github.com/oracle/javavscode/assets/15714253/cbf2ee08-9e46-4f84-831d-525c730515ee

**Comment by Achal1607** [comment]
Fix available in latest version of the extension. So, closing this issue for now. If you still face this issue feel free to reopen.
