### ISSUE TITLE
Renaming should not blindly replace occurrences in comments

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#57]
Consider the following code:

```java
import java.io.ByteArrayInputStream;
import java.io.IOException;

/**
 * In is common in English text.
 */
class Test {

    void run() throws IOException {
        try(var in = new ByteArrayInputStream(new byte[0])) {
            in.read();
        }
    }

}
```

Now if I rename the `in` variable in the try statement, the `in` in the class' Javadoc is also renamed. I can see how updating comments as well can be useful, but then the extension should figure out which occurrences refer to the replaced variable and which don't (which, in the general case, would be extremely hard to determine). For example in this case, I'm renaming a local variable, so I'd never refer to it in the class' Javadoc.

**Comment by jcsahnwaldt** [comment]
I ran into this as well, but only occurrences in the comment on the current method were affected. My workaround: temporarily detach the Javadoc comment from the method by inserting a field declaration, rename the variable, remove the dummy field.

```
/**
 * Method comment, containing the word "name".
 */
int dummy;

void func() {
  int name = 0;  // now I can rename `name` without affecting the word in the comment.
}
```

**Comment by Achal1607** [comment]
Merged
