### ISSUE TITLE
Only give relevant quick fixes w.r.t. "Remove unused ..."

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#59]
See the image below. I did quick fix (`Ctrl + .`) on the variable x in the method run.

* quick fixes should be unique, there are several occurrences of `Remove all unused imports` and `Remove unused import`
* quick fixes should be useful: the occurrences of `Remove unused import` don't tell me *which* import
* quick fixes should apply to the yellow underlined element, so I'd expect only a single warning in this case: `Remove unused "x"`

![image](https://github.com/oracle/javavscode/assets/15714253/468a37ef-b09e-4bcc-a50c-d83d359ade0f)

**Comment by Achal1607** [comment]
Raised PR on netbeans: https://github.com/apache/netbeans/pull/7353
