### ISSUE TITLE
"The collection is only added to, never read" warning doesn't detect forEach

### ISSUE THREAD

**Issue by phraktle** [oracle/javavscode#62]
If a collection has `foo.forEach( ... )` invoked, it should be considered a read operation.

**Comment by Achal1607** [comment]
It tried to reproduce it and can confirm it is a bug that we need to solve.
![image](https://github.com/oracle/javavscode/assets/55803675/8a71179c-efe7-492f-bf91-596a69a09d90)

**Comment by lahodaj** [comment]
See also:
https://github.com/apache/netbeans/issues/5659

**Comment by Achal1607** [comment]
Merged PR
