### ISSUE TITLE
Command 'Download, install and use JDK' resulted in an error   command 'jdk.download.jdk' not found

### ISSUE THREAD

**Issue by phramusca** [oracle/javavscode#71]
Hi. I have just installed the extension to be able to easily install and setup JDK versions. Unfortuneatly, I get a popup error: Command 'Download, install and use JDK' resulted in an error   command 'jdk.download.jdk' not found :( Please help

**Comment by Achal1607** [comment]
There should be any Java project or file open in the workspace to use `Download, install and use JDK` command for now. But I would  try to make this command working without any project open in the workspace as well in the future releases.
Thanks
