### ISSUE TITLE
No support for parameter hints

### ISSUE THREAD

**Issue by gayanper** [oracle/javavscode#76]
When on a method invocation or constructor invocation trying to invoke parameter hints doesn't work using CMD+Shift+Space. It seems that the extension doesn't provide symbol information provider which is checked in the vscode command for parameter hints.

**Comment by lahodaj** [comment]
FWIW, `signatureHelp` (which I think is the protocol method for this) is implemented in the upcoming NB 20:
https://github.com/apache/netbeans/commit/68222f26491c6b9ea886f18605e4f9443b45fc34

So, when we upgrade to NB 20, we should get this.

**Comment by Achal1607** [comment]
Merged
