### ISSUE TITLE
Generated methods not recognized

### ISSUE THREAD

**Issue by rtbunkerlw** [oracle/javavscode#94]
We're using the jackson json annotations.  Code is marked with an `@JsonProperty` annotation which causes getters and setters to be generated.  However, the getter methods are elsewhere being marked as not found.
This seems to be an issue in general with annotation generated code.  For a repro, you can use this example project with lombok.

https://github.com/eugenp/tutorials/tree/master/lombok-modules/lombok

If you load the project in vscode you'll see for example the `src/main/java/com/baeldung/lombok/builder/ClientBuilder.java` file has an error calling the `ImmutableClient` constructor which is auto-generated.

**Comment by Achal1607** [comment]
This extension is focused towards Java development and directly Java related issues, Lombok doesn't follow Java so closing this issue. But if you have face any Java related or extension related issue please feel free to open an issue.

**Comment by rtbunkerlw** [comment]
I don't understand the won't fix here?  The issue i'm highlighting is that methods autogenerated by java annotations are not getting found.  I'm using the lombok project as an example to demonstrate the issue, but it otherwise has nothing to do with lombok.  it's a java annotations issue.

**Comment by robaho** [comment]
Usually you need to add the generated classes directory to the gradle/maven classpath.

**Comment by pbodnar** [comment]
@Achal1607, @rtbunkerlw, I don't quite understand the closing comment either. If anything, I believe this could be closed rather as a _duplicate_ of #83 (as per [my comment](https://github.com/oracle/javavscode/issues/42#issuecomment-1978497448)), where more in-depth conversation has been going on already.

**Comment by rtbunkerlw** [comment]
Thanks @pbodnar, agreed that it's a duplicate.
