### ISSUE TITLE
No support for @SupressWarnings

### ISSUE THREAD

**Issue by psaraviaq** [oracle/javavscode#96]
Unused variables are still underlined even when SupressWarnings is applied. This did not happen when working with the RedHat extension.

```
@SuppressWarnings("unused")
public class Abstraction {

    public static void main(String[] args) {
        Object object = new Object();
    }
}
```

![image](https://github.com/oracle/javavscode/assets/102195797/cda5706c-9a5a-48af-9737-fb24f0061ad5)
![image](https://github.com/oracle/javavscode/assets/102195797/9d5143fc-ef70-4ab9-8843-de92e320b981)

**Comment by pbodnar** [comment]
Findings from my testing:

1. `@SuppressWarnings("unused")` really is ignored, while others, like `@SuppressWarnings("static-access")` are correctly honored.
2. Unlike the Red Hat extension, this one doesn't seem to supply Quick Fix for adding/extending `@SuppressWarnings` for any type of suppressible problem.

**Comment by Achal1607** [comment]
PR raised on Netbeans side to fix this issue: https://github.com/apache/netbeans/pull/7548

**Comment by Achal1607** [comment]
PR merged would be available in NB-23
