### ISSUE TITLE
No recognition of classes in same directory

### ISSUE THREAD

**Issue by PedroSaraviaQ** [oracle/javavscode#97]
For example, If I want to extend a class defined in the same directory, it just doesn't recognize it. However it compiles and runs fine.
![image](https://github.com/oracle/javavscode/assets/102195797/ac1b2e90-9128-4db0-8f4a-740befe76b5c)

**Comment by Achal1607** [comment]
This issue would get resolved when new version of extension is released. 
Note: after that if you use JDK 22 for running the extension it would resolve the issue

**Comment by Achal1607** [comment]
Fixed in current release.
