### ISSUE TITLE
vscjava.vscode-maven-0.43.0/resources/projectTemplate: Error reading project model: For artifact {null:null:1.0-SNAPSHOT:jar}: The groupId cannot be empty.

### ISSUE THREAD

**Issue by archenroot** [oracle/javavscode#99]
After installing the extension it prints out error:
`Project /home/zangetsu/.vscode-server/extensions/vscjava.vscode-maven-0.43.0/resources/projectTemplate: Error reading project model: For artifact {null:null:1.0-SNAPSHOT:jar}: The groupId cannot be empty.`

**Comment by Achal1607** [comment]
Hey @archenroot,
Can you please provide some steps to reproduce this issue?

**Comment by Achal1607** [comment]
Since no response, closing this issue for now.
Feel free to open this issue @archenroot again.
